
export const INIT_SOCKET = "INIT_SOCKET"
export const INIT_SOCKET_SUCCESS = "INIT_SOCKET_SUCCESS"
export const INIT_SOCKET_FAIL = "INIT_SOCKET_FAIL"

export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET"
export const DISCONNECT_SOCKET_SUCCESS = "DISCONNECT_SOCKET_SUCCESS"
export const DISCONNECT_SOCKET_FAIL = "DISCONNECT_SOCKET_FAIL"