# fly.toml app configuration file generated for long-phuong-backend-fragrant-silence-300
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'long-phuong-backend-fragrant-silence-300'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  PORT = "5501"
  SECRETKEY = "@LongPhuong@"
  IS_API = "false"
  # Note: Sensitive values like DATABASE_URL should be set using 'fly secrets set'
  # but we're including a placeholder here

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
