import { ChessType } from "@/common/constants/Enum";

export const listPiecesOrange = [
  {
    id: 1,
    name: "XC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Xa,
    position: { row: 0, col: 0 },
  },
  {
    id: 2,
    name: "KC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Ki,
    position: { row: 0, col: 1 },
  },
  {
    id: 3,
    name: "SC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Si,
    position: { row: 0, col: 2 },
  },
  {
    id: 4,
    name: "TC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Tuong,
    position: { row: 0, col: 3 },
  },
  {
    id: 5,
    name: "VC",
    team: [],
    teamType: "C",
    isRotate: false,
    isTeam: false,
    rotate: 0,
    type: ChessType.Vuong,
    position: { row: 0, col: 4 },
  },
  {
    id: 6,
    name: "TC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Tuong,
    position: { row: 0, col: 5 },
  },
  {
    id: 7,
    name: "SC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Si,
    position: { row: 0, col: 6 },
  },
  {
    id: 8,
    name: "KC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Ki,
    position: { row: 0, col: 7 },
  },
  {
    id: 9,
    name: "XC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Xa,
    position: { row: 0, col: 8 },
  },
];
export const solsTempOrange = [
  {
    id: 12,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 1,
    name: "XC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Xa,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 2,
    name: "KC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Ki,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 3,
    name: "SC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Si,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 4,
    name: "TC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Tuong,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 10,
    name: "LC",
    team: [],
    teamType: "C",
    isRotate: false,
    rotate: 180,
    type: ChessType.Long,
    quantity: 1,
    position: { row: -1, col: -1 },
  },
  {
    id: 11,
    name: "PC",
    team: [],
    teamType: "C",
    isRotate: false,
    rotate: 180,
    type: ChessType.Phuong,
    quantity: 1,
    position: { row: -1, col: -1 },
  },
];
export const solsOrange = [
  {
    id: 12,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 0 },
  },
  {
    id: 13,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 1 },
  },
  {
    id: 14,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 2 },
  },
  {
    id: 15,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 3 },
  },
  {
    id: 16,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 4 },
  },
  {
    id: 17,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 5 },
  },
  {
    id: 18,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 6 },
  },
  {
    id: 19,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 7 },
  },
  {
    id: 20,
    name: "BC",
    team: [],
    teamType: "C",
    isRotate: true,
    rotate: 0,
    type: ChessType.Binh,
    position: { row: 2, col: 8 },
  },
];
export const solsGreen = [
  {
    id: 21,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 0 },
  },
  {
    id: 22,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 1 },
  },
  {
    id: 23,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 2 },
  },
  {
    id: 24,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 3 },
  },
  {
    id: 25,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 4 },
  },
  {
    id: 26,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 5 },
  },
  {
    id: 27,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 6 },
  },
  {
    id: 28,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 7 },
  },
  {
    id: 29,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    position: { row: 6, col: 8 },
  },
];
export const solsTempGreen = [
  {
    id: 21,
    name: "BX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Binh,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 32,
    name: "XX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Xa,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 33,
    name: "KX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Ki,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 34,
    name: "SX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Si,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 35,
    name: "TX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Tuong,
    quantity: 0,
    position: { row: -1, col: -1 },
  },
  {
    id: 30,
    name: "LX",
    team: [],
    teamType: "X",
    isRotate: false,
    rotate: 180,
    type: ChessType.Long,
    quantity: 1,
    position: { row: -1, col: -1 },
  },
  {
    id: 31,
    name: "PX",
    team: [],
    teamType: "X",
    isRotate: false,
    rotate: 180,
    type: ChessType.Phuong,
    quantity: 1,
    position: { row: -1, col: -1 },
  },
];
export const listPiecesGreen = [
  {
    id: 32,
    name: "XX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Xa,
    position: { row: 8, col: 0 },
  },
  {
    id: 33,
    name: "KX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Ki,
    position: { row: 8, col: 1 },
  },
  {
    id: 34,
    name: "SX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Si,
    position: { row: 8, col: 2 },
  },
  {
    id: 35,
    name: "TX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Tuong,
    position: { row: 8, col: 3 },
  },
  {
    id: 36,
    name: "VX",
    team: [],
    teamType: "X",
    isRotate: false,
    rotate: 0,
    type: ChessType.Vuong,
    position: { row: 8, col: 4 },
  },
  {
    id: 37,
    name: "TX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Tuong,
    position: { row: 8, col: 5 },
  },
  {
    id: 38,
    name: "SX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Si,
    position: { row: 8, col: 6 },
  },
  {
    id: 39,
    name: "KX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Ki,
    position: { row: 8, col: 7 },
  },
  {
    id: 40,
    name: "XX",
    team: [],
    teamType: "X",
    isRotate: true,
    rotate: 180,
    type: ChessType.Xa,
    position: { row: 8, col: 8 },
  },
];
